package matching

import "regexp"

const (
	PartExtension = "extension"
	PartFilename  = "filename"
	PartPath      = "path"
)

var Signatures = []Signature{
	SimpleSignature{
		Part:        PartExtension,
		MatchOn:       ".pem",
		Description: "Potential cryptographic private key",
		Comment:     "",
	},
	SimpleSignature{
		Part:        PartExtension,
		MatchOn:       ".log",
		Description: "Log file",
		Comment:     "Log files can contain secret HTTP endpoints, session IDs, API keys and other goodies",
	},
	SimpleSignature{
		Part:        PartExtension,
		MatchOn:       ".pkcs12",
		Description: "Potential cryptographic key bundle",
		Comment:     "",
	},
	SimpleSignature{
		Part:        PartExtension,
		MatchOn:       ".p12",
		Description: "Potential cryptographic key bundle",
		Comment:     "",
	},
	SimpleSignature{
		Part:        PartExtension,
		MatchOn:       ".pfx",
		Description: "Potential cryptographic key bundle",
		Comment:     "",
	},
	SimpleSignature{
		Part:        PartExtension,
		MatchOn:       ".asc",
		Description: "Potential cryptographic key bundle",
		Comment:     "",
	},
	SimpleSignature{
		Part:        PartFilename,
		MatchOn:       "otr.private_key",
		Description: "Pidgin OTR private key",
		Comment:     "",
	},
	SimpleSignature{
		Part:        PartExtension,
		MatchOn:       ".ovpn",
		Description: "OpenVPN client configuration file",
		Comment:     "",
	},
	SimpleSignature{
		Part:        PartExtension,
		MatchOn:       ".cscfg",
		Description: "Azure service configuration schema file",
		Comment:     "",
	},
	SimpleSignature{
		Part:        PartExtension,
		MatchOn:       ".rdp",
		Description: "Remote Desktop connection file",
		Comment:     "",
	},
	SimpleSignature{
		Part:        PartExtension,
		MatchOn:       ".mdf",
		Description: "Microsoft SQL database file",
		Comment:     "",
	},
	SimpleSignature{
		Part:        PartExtension,
		MatchOn:       ".sdf",
		Description: "Microsoft SQL server compact database file",
		Comment:     "",
	},
	SimpleSignature{
		Part:        PartExtension,
		MatchOn:       ".sqlite",
		Description: "SQLite database file",
		Comment:     "",
	},
	SimpleSignature{
		Part:        PartExtension,
		MatchOn:       ".bek",
		Description: "Microsoft BitLocker recovery key file",
		Comment:     "",
	},
	SimpleSignature{
		Part:        PartExtension,
		MatchOn:       ".tpm",
		Description: "Microsoft BitLocker Trusted Platform Module password file",
		Comment:     "",
	},
	SimpleSignature{
		Part:        PartExtension,
		MatchOn:       ".fve",
		Description: "Windows BitLocker full volume encrypted data file",
		Comment:     "",
	},
	SimpleSignature{
		Part:        PartExtension,
		MatchOn:       ".jks",
		Description: "Java keystore file",
		Comment:     "",
	},
	SimpleSignature{
		Part:        PartExtension,
		MatchOn:       ".psafe3",
		Description: "Password Safe database file",
		Comment:     "",
	},
	SimpleSignature{
		Part:        PartFilename,
		MatchOn:       "secret_token.rb",
		Description: "Ruby On Rails secret token configuration file",
		Comment:     "If the Rails secret token is known, it can allow for remote code execution (http://www.exploit-db.com/exploits/27527/)",
	},
	SimpleSignature{
		Part:        PartFilename,
		MatchOn:       "carrierwave.rb",
		Description: "Carrierwave configuration file",
		Comment:     "Can contain credentials for cloud storage systems such as Amazon S3 and Google Storage",
	},
	SimpleSignature{
		Part:        PartFilename,
		MatchOn:       "database.yml",
		Description: "Potential Ruby On Rails database configuration file",
		Comment:     "Can contain database credentials",
	},
	SimpleSignature{
		Part:        PartFilename,
		MatchOn:       "omniauth.rb",
		Description: "OmniAuth configuration file",
		Comment:     "The OmniAuth configuration file can contain client application secrets",
	},
	SimpleSignature{
		Part:        PartFilename,
		MatchOn:       "settings.py",
		Description: "Django configuration file",
		Comment:     "Can contain database credentials, cloud storage system credentials, and other secrets",
	},
	SimpleSignature{
		Part:        PartExtension,
		MatchOn:       ".agilekeychain",
		Description: "1Password password manager database file",
		Comment:     "Feed it to Hashcat and see if you're lucky",
	},
	SimpleSignature{
		Part:        PartExtension,
		MatchOn:       ".keychain",
		Description: "Apple Keychain database file",
		Comment:     "",
	},
	SimpleSignature{
		Part:        PartExtension,
		MatchOn:       ".pcap",
		Description: "Network traffic capture file",
		Comment:     "",
	},
	SimpleSignature{
		Part:        PartExtension,
		MatchOn:       ".gnucash",
		Description: "GnuCash database file",
		Comment:     "",
	},
	SimpleSignature{
		Part:        PartFilename,
		MatchOn:       "jenkins.plugins.publish_over_ssh.BapSshPublisherPlugin.xml",
		Description: "Jenkins publish over SSH plugin file",
		Comment:     "",
	},
	SimpleSignature{
		Part:        PartFilename,
		MatchOn:       "credentials.xml",
		Description: "Potential Jenkins credentials file",
		Comment:     "",
	},
	SimpleSignature{
		Part:        PartExtension,
		MatchOn:       ".kwallet",
		Description: "KDE Wallet Manager database file",
		Comment:     "",
	},
	SimpleSignature{
		Part:        PartFilename,
		MatchOn:       "LocalSettings.php",
		Description: "Potential MediaWiki configuration file",
		Comment:     "",
	},
	SimpleSignature{
		Part:        PartExtension,
		MatchOn:       ".tblk",
		Description: "Tunnelblick VPN configuration file",
		Comment:     "",
	},
	SimpleSignature{
		Part:        PartFilename,
		MatchOn:       "Favorites.plist",
		Description: "Sequel Pro MySQL database manager bookmark file",
		Comment:     "",
	},
	SimpleSignature{
		Part:        PartFilename,
		MatchOn:       "configuration.user.xpl",
		Description: "Little Snitch firewall configuration file",
		Comment:     "Contains traffic rules for applications",
	},
	SimpleSignature{
		Part:        PartExtension,
		MatchOn:       ".dayone",
		Description: "Day One journal file",
		Comment:     "Now it's getting creepy...",
	},
	SimpleSignature{
		Part:        PartFilename,
		MatchOn:       "journal.txt",
		Description: "Potential jrnl journal file",
		Comment:     "Now it's getting creepy...",
	},
	SimpleSignature{
		Part:        PartFilename,
		MatchOn:       "knife.rb",
		Description: "Chef Knife configuration file",
		Comment:     "Can contain references to Chef servers",
	},
	SimpleSignature{
		Part:        PartFilename,
		MatchOn:       "proftpdpasswd",
		Description: "cPanel backup ProFTPd credentials file",
		Comment:     "Contains usernames and password hashes for FTP accounts",
	},
	SimpleSignature{
		Part:        PartFilename,
		MatchOn:       "robomongo.json",
		Description: "Robomongo MongoDB manager configuration file",
		Comment:     "Can contain credentials for MongoDB databases",
	},
	SimpleSignature{
		Part:        PartFilename,
		MatchOn:       "filezilla.xml",
		Description: "FileZilla FTP configuration file",
		Comment:     "Can contain credentials for FTP servers",
	},
	SimpleSignature{
		Part:        PartFilename,
		MatchOn:       "recentservers.xml",
		Description: "FileZilla FTP recent servers file",
		Comment:     "Can contain credentials for FTP servers",
	},
	SimpleSignature{
		Part:        PartFilename,
		MatchOn:       "ventrilo_srv.ini",
		Description: "Ventrilo server configuration file",
		Comment:     "Can contain passwords",
	},
	SimpleSignature{
		Part:        PartFilename,
		MatchOn:       "terraform.tfvars",
		Description: "Terraform variable config file",
		Comment:     "Can contain credentials for terraform providers",
	},
	SimpleSignature{
		Part:        PartFilename,
		MatchOn:       ".exports",
		Description: "Shell configuration file",
		Comment:     "Shell configuration files can contain passwords, API keys, hostnames and other goodies",
	},
	SimpleSignature{
		Part:        PartFilename,
		MatchOn:       ".functions",
		Description: "Shell configuration file",
		Comment:     "Shell configuration files can contain passwords, API keys, hostnames and other goodies",
	},
	SimpleSignature{
		Part:        PartFilename,
		MatchOn:       ".extra",
		Description: "Shell configuration file",
		Comment:     "Shell configuration files can contain passwords, API keys, hostnames and other goodies",
	},
	PatternSignature{
		Part:        PartFilename,
		MatchOn:       regexp.MustCompile(`^.*_rsa$`),
		Description: "Private SSH key",
		Comment:     "",
	},
	PatternSignature{
		Part:        PartFilename,
		MatchOn:       regexp.MustCompile(`^.*_dsa$`),
		Description: "Private SSH key",
		Comment:     "",
	},
	PatternSignature{
		Part:        PartFilename,
		MatchOn:       regexp.MustCompile(`^.*_ed25519$`),
		Description: "Private SSH key",
		Comment:     "",
	},
	PatternSignature{
		Part:        PartFilename,
		MatchOn:       regexp.MustCompile(`^.*_ecdsa$`),
		Description: "Private SSH key",
		Comment:     "",
	},
	PatternSignature{
		Part:        PartPath,
		MatchOn:       regexp.MustCompile(`\.?ssh/config$`),
		Description: "SSH configuration file",
		Comment:     "",
	},
	PatternSignature{
		Part:        PartExtension,
		MatchOn:       regexp.MustCompile(`^key(pair)?$`),
		Description: "Potential cryptographic private key",
		Comment:     "",
	},
	PatternSignature{
		Part:        PartFilename,
		MatchOn:       regexp.MustCompile(`^\.?(bash_|zsh_|sh_|z)?history$`),
		Description: "Shell command history file",
		Comment:     "",
	},
	PatternSignature{
		Part:        PartFilename,
		MatchOn:       regexp.MustCompile(`^\.?mysql_history$`),
		Description: "MySQL client command history file",
		Comment:     "",
	},
	PatternSignature{
		Part:        PartFilename,
		MatchOn:       regexp.MustCompile(`^\.?psql_history$`),
		Description: "PostgreSQL client command history file",
		Comment:     "",
	},
	PatternSignature{
		Part:        PartFilename,
		MatchOn:       regexp.MustCompile(`^\.?pgpass$`),
		Description: "PostgreSQL password file",
		Comment:     "",
	},
	PatternSignature{
		Part:        PartFilename,
		MatchOn:       regexp.MustCompile(`^\.?irb_history$`),
		Description: "Ruby IRB console history file",
		Comment:     "",
	},
	PatternSignature{
		Part:        PartPath,
		MatchOn:       regexp.MustCompile(`\.?purple/accounts\.xml$`),
		Description: "Pidgin chat client account configuration file",
		Comment:     "",
	},
	PatternSignature{
		Part:        PartPath,
		MatchOn:       regexp.MustCompile(`\.?xchat2?/servlist_?\.conf$`),
		Description: "Hexchat/XChat IRC client server list configuration file",
		Comment:     "",
	},
	PatternSignature{
		Part:        PartPath,
		MatchOn:       regexp.MustCompile(`\.?irssi/config$`),
		Description: "Irssi IRC client configuration file",
		Comment:     "",
	},
	PatternSignature{
		Part:        PartPath,
		MatchOn:       regexp.MustCompile(`\.?recon-ng/keys\.db$`),
		Description: "Recon-ng web reconnaissance framework API key database",
		Comment:     "",
	},
	PatternSignature{
		Part:        PartFilename,
		MatchOn:       regexp.MustCompile(`^\.?dbeaver-data-sources.xml$`),
		Description: "DBeaver SQL database manager configuration file",
		Comment:     "",
	},
	PatternSignature{
		Part:        PartFilename,
		MatchOn:       regexp.MustCompile(`^\.?muttrc$`),
		Description: "Mutt e-mail client configuration file",
		Comment:     "",
	},
	PatternSignature{
		Part:        PartFilename,
		MatchOn:       regexp.MustCompile(`^\.?s3cfg$`),
		Description: "S3cmd configuration file",
		Comment:     "",
	},
	PatternSignature{
		Part:        PartPath,
		MatchOn:       regexp.MustCompile(`\.?aws/credentials$`),
		Description: "AWS CLI credentials file",
		Comment:     "",
	},
	PatternSignature{
		Part:        PartFilename,
		MatchOn:       regexp.MustCompile(`^sftp-config(\.json)?$`),
		Description: "SFTP connection configuration file",
		Comment:     "",
	},
	PatternSignature{
		Part:        PartFilename,
		MatchOn:       regexp.MustCompile(`^\.?trc$`),
		Description: "T command-line Twitter client configuration file",
		Comment:     "",
	},
	PatternSignature{
		Part:        PartFilename,
		MatchOn:       regexp.MustCompile(`^\.?gitrobrc$`),
		Description: "Well, this is awkward... Gitrob configuration file",
		Comment:     "",
	},
	PatternSignature{
		Part:        PartFilename,
		MatchOn:       regexp.MustCompile(`^\.?(bash|zsh|csh)rc$`),
		Description: "Shell configuration file",
		Comment:     "Shell configuration files can contain passwords, API keys, hostnames and other goodies",
	},
	PatternSignature{
		Part:        PartFilename,
		MatchOn:       regexp.MustCompile(`^\.?(bash_|zsh_)?profile$`),
		Description: "Shell profile configuration file",
		Comment:     "Shell configuration files can contain passwords, API keys, hostnames and other goodies",
	},
	PatternSignature{
		Part:        PartFilename,
		MatchOn:       regexp.MustCompile(`^\.?(bash_|zsh_)?aliases$`),
		Description: "Shell command alias configuration file",
		Comment:     "Shell configuration files can contain passwords, API keys, hostnames and other goodies",
	},
	PatternSignature{
		Part:        PartFilename,
		MatchOn:       regexp.MustCompile(`config(\.inc)?\.php$`),
		Description: "PHP configuration file",
		Comment:     "",
	},
	PatternSignature{
		Part:        PartExtension,
		MatchOn:       regexp.MustCompile(`^key(store|ring)$`),
		Description: "GNOME Keyring database file",
		Comment:     "",
	},
	PatternSignature{
		Part:        PartExtension,
		MatchOn:       regexp.MustCompile(`^kdbx?$`),
		Description: "KeePass password manager database file",
		Comment:     "Feed it to Hashcat and see if you're lucky",
	},
	PatternSignature{
		Part:        PartExtension,
		MatchOn:       regexp.MustCompile(`^sql(dump)?$`),
		Description: "SQL dump file",
		Comment:     "",
	},
	PatternSignature{
		Part:        PartFilename,
		MatchOn:       regexp.MustCompile(`^\.?htpasswd$`),
		Description: "Apache htpasswd file",
		Comment:     "",
	},
	PatternSignature{
		Part:        PartFilename,
		MatchOn:       regexp.MustCompile(`^(\.|_)?netrc$`),
		Description: "Configuration file for auto-login process",
		Comment:     "Can contain username and password",
	},
	PatternSignature{
		Part:        PartPath,
		MatchOn:       regexp.MustCompile(`\.?gem/credentials$`),
		Description: "Rubygems credentials file",
		Comment:     "Can contain API key for a rubygems.org account",
	},
	PatternSignature{
		Part:        PartFilename,
		MatchOn:       regexp.MustCompile(`^\.?tugboat$`),
		Description: "Tugboat DigitalOcean management tool configuration",
		Comment:     "",
	},
	PatternSignature{
		Part:        PartPath,
		MatchOn:       regexp.MustCompile(`doctl/config.yaml$`),
		Description: "DigitalOcean doctl command-line client configuration file",
		Comment:     "Contains DigitalOcean API key and other information",
	},
	PatternSignature{
		Part:        PartFilename,
		MatchOn:       regexp.MustCompile(`^\.?git-credentials$`),
		Description: "git-credential-store helper credentials file",
		Comment:     "",
	},
	PatternSignature{
		Part:        PartPath,
		MatchOn:       regexp.MustCompile(`config/hub$`),
		Description: "GitHub Hub command-line client configuration file",
		Comment:     "Can contain GitHub API access token",
	},
	PatternSignature{
		Part:        PartFilename,
		MatchOn:       regexp.MustCompile(`^\.?gitconfig$`),
		Description: "Git configuration file",
		Comment:     "",
	},
	PatternSignature{
		Part:        PartPath,
		MatchOn:       regexp.MustCompile(`\.?chef/(.*)\.pem$`),
		Description: "Chef private key",
		Comment:     "Can be used to authenticate against Chef servers",
	},
	PatternSignature{
		Part:        PartPath,
		MatchOn:       regexp.MustCompile(`etc/shadow$`),
		Description: "Potential Linux shadow file",
		Comment:     "Contains hashed passwords for system users",
	},
	PatternSignature{
		Part:        PartPath,
		MatchOn:       regexp.MustCompile(`etc/passwd$`),
		Description: "Potential Linux passwd file",
		Comment:     "Contains system user information",
	},
	PatternSignature{
		Part:        PartFilename,
		MatchOn:       regexp.MustCompile(`^\.?dockercfg$`),
		Description: "Docker configuration file",
		Comment:     "Can contain credentials for public or private Docker registries",
	},
	PatternSignature{
		Part:        PartFilename,
		MatchOn:       regexp.MustCompile(`^\.?npmrc$`),
		Description: "NPM configuration file",
		Comment:     "Can contain credentials for NPM registries",
	},
	PatternSignature{
		Part:        PartFilename,
		MatchOn:       regexp.MustCompile(`^\.?env$`),
		Description: "Environment configuration file",
		Comment:     "",
	},
	PatternSignature{
		Part:        PartPath,
		MatchOn:       regexp.MustCompile(`credential`),
		Description: "Contains word: credential",
		Comment:     "",
	},
	PatternSignature{
		Part:        PartPath,
		MatchOn:       regexp.MustCompile(`password`),
		Description: "Contains word: password",
		Comment:     "",
	},
	SimpleSignature{
		Part:        PartFilename,
		MatchOn:       "credentials.json",
		Description: "Google Cloud Platform service account credentials keyfile",
		Comment:     "GCP service account credentials can be activated using the gcloud command from Google's Cloud SDK (https://cloud.google.com/sdk/gcloud/reference/auth/activate-service-account)",
	},
	PatternSignature{
		Part:        PartFilename,
		MatchOn:       regexp.MustCompile(`^.*-[a-f0-9]{12}\.json$`),
		Description: "Google Cloud Platform service account credentials keyfile",
		Comment:     "GCP service account credentials can be activated using the gcloud command from Google's Cloud SDK (https://cloud.google.com/sdk/gcloud/reference/auth/activate-service-account)",
	},
	SimpleSignature{
		Part:        PartFilename,
		MatchOn:       "adc.json",
		Description: "Legacy Google Cloud Platform service account credentials keyfile",
		Comment:     "GCP service account credentials can be activated using the gcloud command from Google's Cloud SDK (https://cloud.google.com/sdk/gcloud/reference/auth/activate-service-account)",
	},
	SimpleSignature{
		Part:        PartFilename,
		MatchOn:       "credentials.db",
		Description: "Google Cloud Platform gcloud credential database",
		Comment:     "sqlite database containing credentials used by the gcloud command from Google's Cloud SDK",
	},
	SimpleSignature{
		Part:        PartFilename,
		MatchOn:       ".boto",
		Description: "Legacy Google Cloud Platform gcloud credential database",
		Comment:     "File containing credentials used by the gcloud command from Google's Cloud SDK",
	},
}